// Unit tests for aleph.flow:laplacian.
//
// Oracles ported verbatim from
//   aleph-engine/aleph-flow/src/laplacian.rs  (the #[cfg(test)] module).
//
// Tolerances are copied EXACTLY from the Rust tests, NOT weakened:
//   - 4-cycle symmetric    : is_symmetric(1e-9)
//   - 4-cycle ones-in-kernel: ones_in_kernel(1e-9)   (every row sums to 0)
//   - empty graph          : matrix.rows() == 0, curvatures.size() == 0
//   - isolated meshes       : zero matrix to 1e-12   (flow_smoke parity)
//
// Plus the 4d-plan certificates for the weighted Laplacian:
//   - PSD on 256 random graphs (LDLT factorize succeeds -> no negative pivot)
//   - row sums = 0 on every random graph
// Random graphs are generated by a deterministic xorshift PRNG so the suite is
// reproducible (spec 7.5 determinism).
//
// Graphs are built via the real Graph -> OneSkeleton pipeline (Mesh + Adjacent
// edges), the same public surface the Rust tests use through build_laplacian.

#include "doctest.h"

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

import aleph.flow;
import aleph.graph;
import aleph.types;
import aleph.linalg.sparse;
import aleph.math;

using aleph::flow::build_laplacian;
using aleph::flow::default_weight;
using aleph::flow::WeightedLaplacian;
using aleph::graph::Graph;
using aleph::linalg::sparse::DMatrix;
using aleph::linalg::sparse::LDLT;
using aleph::math::f64;
using aleph::types::EdgeKind;
using aleph::types::Mesh;
using aleph::types::NodeId;

namespace {

// n-cycle of Mesh vertices joined by Adjacent edges (port of the Rust
// `n_cycle` helper). Edges (i, (i+1) % n).
Graph n_cycle(std::size_t n) {
    Graph               g;
    std::vector<NodeId> ms;
    ms.reserve(n);
    for (std::size_t i = 0; i < n; ++i) {
        const NodeId id = g.alloc_node_id();
        g.insert_node(Mesh{id, std::string("m") + std::to_string(i), 1});
        ms.push_back(id);
    }
    for (std::size_t i = 0; i < n; ++i) {
        auto r = g.add_edge(EdgeKind::Adjacent, ms[i], ms[(i + 1) % n]);
        REQUIRE(r.has_value());
    }
    return g;
}

// Deterministic 64-bit xorshift PRNG (reproducible random graphs, spec 7.5).
struct Xorshift {
    std::uint64_t s;
    explicit Xorshift(std::uint64_t seed) : s(seed ? seed : 0x9e3779b97f4a7c15ULL) {}
    std::uint64_t next() {
        s ^= s << 13;
        s ^= s >> 7;
        s ^= s << 17;
        return s;
    }
    // Uniform in [0, bound).
    std::size_t below(std::size_t bound) {
        return static_cast<std::size_t>(next() % bound);
    }
};

// Random Mesh graph with `n` vertices and `m` distinct Adjacent edges drawn
// from the given PRNG. Self-loops and duplicate edges are skipped.
Graph random_mesh_graph(Xorshift& rng, std::size_t n, std::size_t m) {
    Graph               g;
    std::vector<NodeId> ms;
    ms.reserve(n);
    for (std::size_t i = 0; i < n; ++i) {
        const NodeId id = g.alloc_node_id();
        g.insert_node(Mesh{id, std::string("m") + std::to_string(i), 1});
        ms.push_back(id);
    }
    if (n < 2) {
        return g;
    }
    std::size_t added = 0;
    std::size_t guard = 0;
    while (added < m && guard < m * 20 + 50) {
        ++guard;
        const std::size_t a = rng.below(n);
        const std::size_t b = rng.below(n);
        if (a == b) {
            continue;
        }
        auto r = g.add_edge(EdgeKind::Adjacent, ms[a], ms[b]);
        if (r.has_value()) {
            ++added;
        }
    }
    return g;
}

}  // namespace

// 4-cycle: each vertex degree 2, kappa = 0 on every edge, so w = 1 + 0 = 1.
// Delta is the symmetric unit-weight cycle Laplacian.
// (port laplacian_4cycle_symmetric, tolerance 1e-9 verbatim.)
TEST_CASE("laplacian_4cycle_symmetric") {
    const Graph             g = n_cycle(4);
    const WeightedLaplacian l = build_laplacian(g, default_weight);
    CHECK(l.is_symmetric(1e-9));
}

// 4-cycle: the all-ones vector lies in the kernel (every row of Delta sums to 0).
// (port laplacian_4cycle_ones_in_kernel, tolerance 1e-9 verbatim.)
TEST_CASE("laplacian_4cycle_ones_in_kernel") {
    const Graph             g = n_cycle(4);
    const WeightedLaplacian l = build_laplacian(g, default_weight);
    CHECK(l.ones_in_kernel(1e-9));
}

// Empty graph -> empty Laplacian, empty curvature map.
// (port laplacian_empty_graph.)
TEST_CASE("laplacian_empty_graph") {
    const Graph             g;
    const WeightedLaplacian l = build_laplacian(g, default_weight);
    CHECK(l.matrix.rows() == 0);
    CHECK(l.curvatures.size() == 0);
}

// Three isolated meshes, no edges -> Delta is the 3x3 zero matrix
// (flow_smoke.rs isolated_meshes_yield_zero_matrix parity, 1e-12).
TEST_CASE("laplacian_isolated_meshes_zero_matrix") {
    Graph g;
    for (std::size_t i = 0; i < 3; ++i) {
        const NodeId id = g.alloc_node_id();
        g.insert_node(Mesh{id, std::string("m") + std::to_string(i), 1});
    }
    const WeightedLaplacian l = build_laplacian(g, default_weight);
    CHECK(l.node_order.size() == 3);
    REQUIRE(l.matrix.rows() == 3);
    REQUIRE(l.matrix.cols() == 3);
    for (std::size_t r = 0; r < 3; ++r) {
        for (std::size_t c = 0; c < 3; ++c) {
            CHECK(std::abs(l.matrix.at(r, c)) < 1e-12);
        }
    }
}

// 4d-plan certificate: Delta is symmetric PSD with zero row sums on 256 random
// graphs. With non-negative weights (default_weight clamps w >= 0.05) every
// weighted graph Laplacian is symmetric PSD; LDLT::factorize accepts singular
// PSD matrices and only errors (NotPsd) on a negative pivot, so a successful
// factorization is the PSD certificate.
TEST_CASE("laplacian_psd_and_zero_row_sums_on_256_random_graphs") {
    Xorshift rng(0xA1EF10C0DEULL);
    for (std::size_t trial = 0; trial < 256; ++trial) {
        const std::size_t n = 2 + rng.below(7);   // 2..=8 vertices
        const std::size_t m = 1 + rng.below(2 * n);
        const Graph       g = random_mesh_graph(rng, n, m);

        const WeightedLaplacian l = build_laplacian(g, default_weight);

        // Symmetric.
        CHECK(l.is_symmetric(1e-9));

        // Every row sums to 0 (constant vector in the kernel).
        CHECK(l.ones_in_kernel(1e-9));
        const std::size_t rows = l.matrix.rows();
        for (std::size_t r = 0; r < rows; ++r) {
            f64 row_sum = 0.0;
            for (std::size_t c = 0; c < l.matrix.cols(); ++c) {
                row_sum += l.matrix.at(r, c);
            }
            CHECK(std::abs(row_sum) < 1e-9);
        }

        // PSD: LDLT factorization succeeds (no negative pivot).
        if (rows > 0) {
            const auto fac = LDLT::factorize(l.matrix);
            CHECK(fac.has_value());
            if (fac.has_value()) {
                for (const f64 dval : fac->d) {
                    CHECK(dval >= -1e-9);  // PSD: non-negative pivots
                }
            }
        }
    }
}
